=== lollopelle01/BEng-CompEng/Computer Engeneering/3_year/PAWeb/PAW_workspace/Volo/src/it/unibo/paw/sources/volo.xsd
<?xml version="1.0" encoding="utf-8" ?>

<!-- SCALETTA SCRITTURA SCHEMA -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Definzione sottotipo1 -->
	<xs:simpleType name="tipo_volo">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Andata-Ritorno"/>
			<xs:enumeration value="Solo-Andata"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Definzione sottotipo2 -->
    <xs:complexType name="prenotazione">
		<xs:sequence>
			<xs:element name="codice" type="xs:string"/>
			<xs:element name="compagnia" type="xs:string"/>
			<xs:element name="tipo_volo" type="tipo_volo"/>
			<xs:element name="aeroporto_partenza" type="xs:string"/>
			<xs:element name="dataOra_partenza" type="xs:dateTime"/>
			<xs:element name="aeroporto_arrivo" type="xs:string"/>
			<xs:element name="dataOra_arrivo" type="xs:dateTime"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Definizione per istanza finale -->
	<xs:complexType name="cliente">
		<xs:sequence>
			<xs:element name="nome" type="xs:string"/>
			<xs:element name="cognome" type="xs:string"/>
			<xs:element name="passaporto" type="xs:integer"/>
			<xs:element name="prenotazione" type="prenotazione" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
    <xs:complexType name="archivio">
		<xs:sequence>
			<xs:element name="cliente" type="cliente" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	

	<!-- Istanza finale -->
	<xs:element name="archivio" type="archivio"/>
</xs:schema>

=== lollopelle01/BEng-CompEng/Computer Engeneering Bachelor/3_year/PAWeb/PAW_workspace/Volo/bin/it/unibo/paw/sources/volo.xml
<?xml version="1.0" encoding="UTF-8"?>
<archivio xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="volo.xsd">
	<cliente>
		<nome>Lorenzo</nome>
		<cognome>Pellegrino</cognome>
		<passaporto>123456789</passaporto>
		
		<prenotazione>
			<codice>ABCDEF</codice>
			<compagnia>Ryanair</compagnia>
			<tipo_volo>Solo-Andata</tipo_volo>
			<aeroporto_partenza>Bologna</aeroporto_partenza>
			<dataOra_partenza>2023-08-29T00:00:00</dataOra_partenza>
			<aeroporto_arrivo>Rimini</aeroporto_arrivo>
			<dataOra_arrivo>2023-08-30T00:00:00</dataOra_arrivo>
		</prenotazione>
		
		<prenotazione>
			<codice>GHIJKL</codice>
			<compagnia>Alitalia</compagnia>
			<tipo_volo>Solo-Andata</tipo_volo>
			<aeroporto_partenza>Bologna</aeroporto_partenza>
			<dataOra_partenza>2023-08-31T00:00:00</dataOra_partenza>
			<aeroporto_arrivo>Atene</aeroporto_arrivo>
			<dataOra_arrivo>2023-09-01T00:00:00</dataOra_arrivo>
		</prenotazione>
	</cliente>
	
	<cliente>
		<nome>Riccardo</nome>
		<cognome>Pellegrino</cognome>
		<passaporto>987654321</passaporto>
		
		<prenotazione>
			<codice>QWERTY</codice>
			<compagnia>Alitalia</compagnia>
			<tipo_volo>Solo-Andata</tipo_volo>
			<aeroporto_partenza>Bologna</aeroporto_partenza>
			<dataOra_partenza>2023-08-29T00:00:00</dataOra_partenza>
			<aeroporto_arrivo>Rimini</aeroporto_arrivo>
			<dataOra_arrivo>2023-08-30T00:00:00</dataOra_arrivo>
		</prenotazione>
		
		<prenotazione>
			<codice>ZXCVBN</codice>
			<compagnia>Alitalia</compagnia>
			<tipo_volo>Andata-Ritorno</tipo_volo>
			<aeroporto_partenza>Bologna</aeroporto_partenza>
			<dataOra_partenza>2023-08-31T00:00:00</dataOra_partenza>
			<aeroporto_arrivo>Atene</aeroporto_arrivo>
			<dataOra_arrivo>2023-09-01T00:00:00</dataOra_arrivo>
		</prenotazione>
	</cliente>
</archivio>
