=== lollopelle01/BEng-CompEng/3_year/PAWeb/PAW_workspace/Pony/src/it/unibo/paw/sources/pony.xsd
<?xml version="1.0" encoding="utf-8" ?>

<!-- SCALETTA SCRITTURA SCHEMA -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Definzione sottotipo1 -->
	<xs:simpleType name="modalita">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GI"/>
			<xs:enumeration value="GG"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Definzione sottotipo2 -->
    <xs:simpleType name="fascia_eta">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]+\-[0-9]+"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- GIOCO DIGITALE -->
	<xs:complexType name="GiocoDigitale">
		<xs:sequence>
			<xs:element name="titolo" type="xs:string"/>
			<xs:element name="autore" type="xs:string"/>
			<xs:element name="casa_produttrice" type="xs:string"/>
			<xs:element name="anno_produzione" type="xs:integer"/>
			<xs:element name="fascia_eta" type="fascia_eta"/>
			<xs:element name="lingua" type="xs:string"/>
			<xs:element name="durata" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- GIOCO TRADIZIONALE -->
	<xs:complexType name="GiocoTradizionale">
		<xs:sequence>
			<xs:element name="nome" type="xs:string"/>
			<xs:element name="autore" type="xs:string"/>
			<xs:element name="marca" type="xs:string"/>
			<xs:element name="fascia_eta" type="fascia_eta"/>
			<xs:element name="lingua" type="xs:string"/>
			<xs:element name="modalita" type="modalita"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="categoria">
		<xs:choice>
			<xs:element name="GD" type="GiocoDigitale"/>
			<xs:element name="GT" type="GiocoTradizionale"/>
		</xs:choice>
	</xs:complexType>

	
	<xs:complexType name="giocattolo">
		<xs:sequence>
			<xs:element name="id" type="xs:string"/>
			<xs:element name="categoria" type="categoria"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Definizione per istanza finale -->
	<xs:complexType name="giocattoli">
		<xs:sequence>
			<xs:element name="giocattolo" type="giocattolo" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Istanza finale -->
	<xs:element name="giocattoli" type="giocattoli"/>
</xs:schema>

=== lollopelle01/BEng-CompEng/Computer Engeneering Bachelor/3_year/PAWeb/PAW_workspace/Pony/src/it/unibo/paw/sources/pony.xml
<?xml version="1.0" encoding="utf-8"?>

<giocattoli xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="pony.xsd">
  
  <giocattolo>
    <id>GD001</id>
    <categoria>
      <GD>
        <titolo>Mio Gioco Digitale</titolo>
        <autore>Autore Digitale</autore>
        <casa_produttrice>Digital Corp.</casa_produttrice>
        <anno_produzione>2023</anno_produzione>
        <fascia_eta>4-6</fascia_eta>
        <lingua>Italiano</lingua>
        <durata>30 min</durata>
      </GD>
    </categoria>
  </giocattolo>
  
  <giocattolo>
    <id>GT001</id>
    <categoria>
      <GT>
        <nome>Puzzle Colorato</nome>
        <autore>Puzzle Master</autore>
        <marca>Puzzle Co.</marca>
        <fascia_eta>6-10</fascia_eta>
        <lingua>Inglese</lingua>
        <modalita>GI</modalita>
      </GT>
    </categoria>
  </giocattolo>
  
  <giocattolo>
    <id>GD002</id>
    <categoria>
      <GD>
        <titolo>Giochi nel Futuro</titolo>
        <autore>Sci-Fi Gamer</autore>
        <casa_produttrice>Future Games Inc.</casa_produttrice>
        <anno_produzione>2030</anno_produzione>
        <fascia_eta>12-18</fascia_eta>
        <lingua>Inglese</lingua>
        <durata>120 min</durata>
      </GD>
    </categoria>
  </giocattolo>
  
  <giocattolo>
    <id>GT002</id>
    <categoria>
      <GT>
        <nome>Cavallo a Dondolo</nome>
        <autore>Tradizione Toys</autore>
        <marca>Classic Co.</marca>
        <fascia_eta>6-8</fascia_eta>
        <lingua>Italiano</lingua>
        <modalita>GI</modalita>
      </GT>
    </categoria>
  </giocattolo>
  
  <giocattolo>
    <id>GD003</id>
    <categoria>
      <GD>
        <titolo>Avventure Spaziali</titolo>
        <autore>Galaxy Gamer</autore>
        <casa_produttrice>Space Games Ltd.</casa_produttrice>
        <anno_produzione>2025</anno_produzione>
        <fascia_eta>8-12</fascia_eta>
        <lingua>Inglese</lingua>
        <durata>60 min</durata>
      </GD>
    </categoria>
  </giocattolo>
  
</giocattoli>
