=== lollopelle01/BEng-CompEng/Computer Engeneering Bachelor/3_year/Tecnologie Web/Templates_telegram/HTML CSS/CSS JS Balda/CSS XML/files/studenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="students">

		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="student" maxOccurs="unbounded">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="sesso" minOccurs="1" maxOccurs="1"
								type="gender" />
							<xs:element name="cap" minOccurs="1" maxOccurs="1"
								type="cap" />
							<xs:element name="universita" minOccurs="1" maxOccurs="1"
								type="uni" />
							<xs:element name="lavoratore" minOccurs="0" maxOccurs="1"
								type="xs:string" />
						</xs:sequence>
						<xs:attribute name="cognomenome" type="name" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="name">
		<xs:restriction base="xs:string">
			<xs:pattern value="([ a-zA-Z])+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="gender">
		<xs:annotation>
			<xs:documentation>
				Gender: male or female
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="M|F" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="cap">
		<xs:annotation>
			<xs:documentation>
				Numeric 5 digit code
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{5}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="uni">
		<xs:annotation>
			<xs:documentation>
				to bo na
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="to" />
			<xs:enumeration value="bo" />
			<xs:enumeration value="na" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== lollopelle01/BEng-CompEng/3_year/Tecnologie Web/Templates_telegram/HTML CSS/CSS JS Balda/CSS XML/files/studenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="studenti.xsd">
	<student cognomenome="bello di papa">
		<sesso>M</sesso>
		<cap>12345</cap>
		<universita>bo</universita>
		<lavoratore>descrizione del lavoro</lavoratore>
	</student>
	<student cognomenome="bella di mamma">
		<sesso>F</sesso>
		<cap>67898</cap>
		<universita>to</universita>
	</student>
	<student cognomenome="bello di zio">
		<sesso>M</sesso>
		<cap>18745</cap>
		<universita>na</universita>
	</student>
</students>
