=== lollopelle01/BEng-CompEng/Computer Engeneering/3_year/PAWeb/PAW_workspace/ArchivioVolo/src/it/unibo/paw/sources/archivioVolo.xsd
<?xml version="1.0" encoding="utf-8" ?>

<!-- SCALETTA SCRITTURA SCHEMA -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="tipo_volo">
		<xs:restriction base="xs:string">
			<xs:pattern value="(Andata-Ritorno|Solo-Andata)"/>
        </xs:restriction>
	</xs:simpleType>


	<xs:complexType name="data">
		<xs:sequence>
			<xs:element name="giorno" type="xs:integer"/>
			<xs:element name="mese" type="xs:integer"/>
			<xs:element name="anno" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ora">
		<xs:sequence>
			<xs:element name="ora" type="xs:integer"/>
			<xs:element name="minuti" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="prenotazione">
		<xs:sequence>
			<xs:element name="codice" type="xs:string"/>
			<xs:element name="nome_compagnia" type="xs:string"/>
			<xs:element name="tipo_volo" type="tipo_volo"/>
			
			<!-- Partenza -->
			<xs:element name="aeroporto_partenza" type="xs:string"/>
			<xs:element name="data_partenza" type="data"/>
			<xs:element name="ora_partenza" type="ora"/>
			
			<!-- Arrivo -->
			<xs:element name="aeroporto_arrivo" type="xs:string"/>
			<xs:element name="data_arrivo" type="data"/>
			<xs:element name="ora_arrivo" type="ora"/>
			
		</xs:sequence>
	</xs:complexType>

    <xs:complexType name="prenotazioni">
		<xs:sequence>
			<xs:element name="prenotazione" type="prenotazione" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="archivio_personale">
		<xs:sequence>
			<xs:element name="nome" type="xs:string"/>
			<xs:element name="cognome" type="xs:string"/>
			<xs:element name="passaporto" type="xs:integer"/>
			<xs:element name="prenotazioni" type="prenotazioni"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Definizione per istanza finale -->
	<xs:complexType name="archivi_personali">
		<xs:sequence>
			<xs:element name="archivio_personale" type="archivio_personale" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Istanza finale -->
	<xs:element name="archivi_personali" type="archivi_personali"/>
</xs:schema>

=== lollopelle01/BEng-CompEng/Computer Engeneering/3_year/PAWeb/PAW_workspace/ArchivioVolo/src/it/unibo/paw/sources/archivioVolo.xml
<archivi_personali xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="archivioVolo.xsd">
    <archivio_personale>
        <nome>Marco</nome>
        <cognome>Rossi</cognome>
        <passaporto>123456789</passaporto>
        <prenotazioni>
            <prenotazione>
                <codice>P123</codice>
                <nome_compagnia>Ryanair</nome_compagnia>
                <tipo_volo>Andata-Ritorno</tipo_volo>
                <aeroporto_partenza>Bologna</aeroporto_partenza>
                <data_partenza>
                    <giorno>15</giorno>
                    <mese>8</mese>
                    <anno>2023</anno>
                </data_partenza>
                <ora_partenza>
                    <ora>10</ora>
                    <minuti>30</minuti>
                </ora_partenza>
                <aeroporto_arrivo>Ryanair</aeroporto_arrivo>
                <data_arrivo>
                    <giorno>16</giorno>
                    <mese>8</mese>
                    <anno>2023</anno>
                </data_arrivo>
                <ora_arrivo>
                    <ora>14</ora>
                    <minuti>45</minuti>
                </ora_arrivo>
            </prenotazione>
            <prenotazione>
                <codice>P124</codice>
                <nome_compagnia>Ryanair</nome_compagnia>
                <tipo_volo>Solo-Andata</tipo_volo>
                <aeroporto_partenza>Aeroporto C</aeroporto_partenza>
                <data_partenza>
                    <giorno>20</giorno>
                    <mese>8</mese>
                    <anno>2023</anno>
                </data_partenza>
                <ora_partenza>
                    <ora>15</ora>
                    <minuti>45</minuti>
                </ora_partenza>
                <aeroporto_arrivo>Bologna</aeroporto_arrivo>
                <data_arrivo>
                    <giorno>20</giorno>
                    <mese>5</mese>
                    <anno>2023</anno>
                </data_arrivo>
                <ora_arrivo>
                    <ora>18</ora>
                    <minuti>30</minuti>
                </ora_arrivo>
            </prenotazione>
        </prenotazioni>
    </archivio_personale>
    <archivio_personale>
        <nome>Giovanna</nome>
        <cognome>Bianchi</cognome>
        <passaporto>987654321</passaporto>
        <prenotazioni>
            <prenotazione>
                <codice>P125</codice>
                <nome_compagnia>Ryanair</nome_compagnia>
                <tipo_volo>Andata-Ritorno</tipo_volo>
                <aeroporto_partenza>Bologna</aeroporto_partenza>
                <data_partenza>
                    <giorno>22</giorno>
                    <mese>8</mese>
                    <anno>2023</anno>
                </data_partenza>
                <ora_partenza>
                    <ora>12</ora>
                    <minuti>0</minuti>
                </ora_partenza>
                <aeroporto_arrivo>ciao</aeroporto_arrivo>
                <data_arrivo>
                    <giorno>23</giorno>
                    <mese>9</mese>
                    <anno>2023</anno>
                </data_arrivo>
                <ora_arrivo>
                    <ora>16</ora>
                    <minuti>30</minuti>
                </ora_arrivo>
            </prenotazione>
            <prenotazione>
                <codice>P126</codice>
                <nome_compagnia>Airline D</nome_compagnia>
                <tipo_volo>Solo-Andata</tipo_volo>
                <aeroporto_partenza>Aeroporto G</aeroporto_partenza>
                <data_partenza>
                    <giorno>25</giorno>
                    <mese>8</mese>
                    <anno>2023</anno>
                </data_partenza>
                <ora_partenza>
                    <ora>9</ora>
                    <minuti>15</minuti>
                </ora_partenza>
                <aeroporto_arrivo>Aeroporto H</aeroporto_arrivo>
                <data_arrivo>
                    <giorno>25</giorno>
                    <mese>8</mese>
                    <anno>2023</anno>
                </data_arrivo>
                <ora_arrivo>
                    <ora>11</ora>
                    <minuti>30</minuti>
                </ora_arrivo>
            </prenotazione>
        </prenotazioni>
    </archivio_personale>
</archivi_personali>
