=== lollopelle01/BEng-CompEng/Computer Engeneering Bachelor/3_year/Tecnologie Web/Templates_telegram/XSD DOM SAX/XSD28062016NavigazioneAlberghi/files/navigazione.xsd
<?xml version="1.0" encoding="UTF-8"?>
   <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="navigazione">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="utente">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="email" type="email" use="required"/>
                                <xs:attribute name="password" type="password" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ricerca">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="risultato" maxOccurs="unbounded">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="nomehotel" minOccurs="1" type="xs:string"/>
                                        <xs:element name="fotografiahotel" minOccurs="1" type="xs:string"/>
                                        <xs:element name="giudizioutenti" minOccurs="1" type="giudizio"/>
                                        <xs:element name="prezzo" minOccurs="1" type="prezzoEuroType"/>
                                        <xs:element name="link" minOccurs="1" >
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:anyURI">
                                                        <xs:attribute name="visitato" type="sino" use="optional" default="no"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nazione" type="xs:string" use="required"/>
                        <xs:attribute name="citta" type="xs:string" use="required"/>
                        <xs:attribute name="numero_stelle" type="numstelle" use="required"/>
                        <xs:attribute name="fascia_prezzo" type="fasciaprezzo" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="sino">
		<xs:annotation>
			<xs:documentation>
				Uno tra due valori (si o no)
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="si|no" />
		</xs:restriction>
	</xs:simpleType>
    
    <xs:simpleType name="prezzoEuroType">
    	<xs:annotation>
            <xs:documentation>
                Prezzo numerico con esattamente 2 decimali
            </xs:documentation>
    	</xs:annotation>
    	<xs:restriction base="xs:decimal">
        	<xs:fractionDigits value="2" />
        	<xs:pattern value="[0-9]+\.[0-9]{2}"></xs:pattern>
    	</xs:restriction>
	</xs:simpleType>
    
    <xs:simpleType name="email">
		<xs:annotation>
			<xs:documentation>
				Email del tipo "prova@dominio.it"
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+@[^@]+\..+" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="password">
    	<xs:annotation>
            <xs:documentation>
                Password di 8 caratteri precisi, tra cui almeno un numero e un {?!*$}
            </xs:documentation>
    	</xs:annotation>
    	<xs:restriction base="xs:string">
        	<xs:length value="8"/>
        	<xs:pattern value=".*[0-9]+.*"/>
        	<xs:pattern value=".*[?!*$]+.*"/>
        </xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="numstelle">
		<xs:annotation>
			<xs:documentation>
				Numero di Stelle tra 1 e 5
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:unsignedShort">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="5"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="fasciaprezzo">
		<xs:annotation>
			<xs:documentation>
				Fascia di prezzo (bassa|media|alta|lusso)
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="bassa" />
			<xs:enumeration value="media" />
			<xs:enumeration value="alta" />
			<xs:enumeration value="lusso" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="giudizio">
		<xs:annotation>
			<xs:documentation>
				Giudizio degli utenti (eccellente|buono|medio|sufficiente|mediocre)
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="eccellente" />
			<xs:enumeration value="buono" />
			<xs:enumeration value="medio" />
			<xs:enumeration value="sufficiente" />
			<xs:enumeration value="mediocre" />
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== lollopelle01/BEng-CompEng/Computer Engeneering/3_year/Tecnologie Web/Templates_telegram/XSD DOM SAX/XSD28062016NavigazioneAlberghi/files/navigazione.xml
<?xml version="1.0" encoding="UTF-8"?>
<navigazione xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="navigazione.xsd">
	<utente email="prova@prova.it" password="0asd!qwe"></utente>
	<ricerca nazione="Italia" citta="Bologna" numero_stelle="4" fascia_prezzo="media">
		<risultato>
			<nomehotel>Hermitage</nomehotel>
			<fotografiahotel>imageHermitage.jpg</fotografiahotel>
			<giudizioutenti>buono</giudizioutenti>
			<prezzo>110.00</prezzo>
			<link visitato="si">http://www.hermitagebologna.it</link>
		</risultato>
		<risultato>
			<nomehotel>Maximo</nomehotel>
			<fotografiahotel>imageMaximo.jpg</fotografiahotel>
			<giudizioutenti>sufficiente</giudizioutenti>
			<prezzo>115.00</prezzo>
			<link visitato="no">http://www.hermitagebologna.it</link>
		</risultato>
	</ricerca>
</navigazione>
