=== lollopelle01/BEng-CompEng/Computer Engeneering Bachelor/3_year/PAWeb/PAW_workspace/Cineteca/bin/it/unibo/paw/sources/Cineteca.xsd
<?xml version="1.0" encoding="utf-8" ?>

<!-- SCALETTA SCRITTURA SCHEMA -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<!-- PER AUDIOVISIVO -->
	<xs:simpleType name="colore">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Colore"/>
			<xs:enumeration value="BN"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="formato">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Blu-ray"/>
			<xs:enumeration value="DVD"/>
			<xs:enumeration value="Divx"/>
			<xs:enumeration value="VHS"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="disponibilita">
		<xs:restriction base="xs:string">
			<xs:enumeration value="si"/>
			<xs:enumeration value="no"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="collocazione">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{2}\.[0-9]{2}\.[0-9]{2}\.[0-9]{3}\.[a-zA-Z]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	
    <xs:complexType name="audiovisivo">
		<xs:sequence>
			<xs:element name="nome" type="xs:string"/>
			<xs:element name="cognome" type="xs:string"/>
			<xs:element name="titolo" type="xs:string"/>
			<xs:element name="nazione" type="xs:string"/>
			<xs:element name="lingua" type="xs:string"/>
			<xs:element name="colore" type="colore"/>
			<xs:element name="durata" type="xs:integer"/>
			<xs:element name="tipologia" type="xs:string"/>
			<xs:element name="formato" type="formato"/>
			<xs:element name="annoProduzione" type="xs:integer"/>
			<xs:element name="disponibilita" type="disponibilita"/>
			<xs:element name="collocazione" type="collocazione"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- PER PELLICOLA -->
	<xs:simpleType name="tipologia">
		<xs:restriction base="xs:string">
			<xs:enumeration value="35mm"/>
			<xs:enumeration value="16mm"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="pellicola">
		<xs:sequence>
			<xs:element name="regia" type="xs:string"/>
			<xs:element name="titolo" type="xs:string"/>
			<xs:element name="buonoStato" type="disponibilita"/>
			<xs:element name="tipologia" type="tipologia"/>			
		</xs:sequence>
	</xs:complexType>

	<!-- Definizione per istanza finale -->
	<xs:complexType name="film">
		<xs:choice>
			<xs:element name="audiovisivo" type="audiovisivo"/>
			<xs:element name="pellicola" type="pellicola"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="films">
		<xs:sequence>
			<xs:element name="film" type="film" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Istanza finale -->
	<xs:element name="archivio" type="films"/>
</xs:schema>

=== lollopelle01/BEng-CompEng/Computer Engeneering Bachelor/3_year/PAWeb/PAW_workspace/Cineteca/bin/it/unibo/paw/sources/Cineteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<archivio xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Cineteca.xsd">
	<!-- PELLICOLE -->
	
	<film>
		<pellicola>
			<regia>Regia 1</regia>
			<titolo>Titolo 1</titolo>
			<buonoStato>si</buonoStato>
			<tipologia>16mm</tipologia>
		</pellicola>
	</film>
	
	<film>
		<pellicola>
			<regia>Regia 2</regia>
			<titolo>Titolo 2</titolo>
			<buonoStato>si</buonoStato>
			<tipologia>16mm</tipologia>
		</pellicola>
	</film>
	
	<film>
		<pellicola>
			<regia>Regia 3</regia>
			<titolo>Titolo 3</titolo>
			<buonoStato>no</buonoStato>
			<tipologia>16mm</tipologia>
		</pellicola>
	</film>
	
	<film>
		<pellicola>
			<regia>Regia 4</regia>
			<titolo>Titolo 4</titolo>
			<buonoStato>si</buonoStato>
			<tipologia>35mm</tipologia>
		</pellicola>
	</film>
	
	
	<!-- AUDIOVISIVI -->
	<film>
		<audiovisivo>
			<nome>Nome 1</nome>
			<cognome>Cognome 1</cognome>
			<titolo>Titolo 5</titolo>
			<nazione>Italia</nazione>
			<lingua>Italiano</lingua>
			<colore>Colore</colore>
			<durata>1000</durata>
			<tipologia>Documentario</tipologia>
			<formato>Blu-ray</formato>
			<annoProduzione>2001</annoProduzione>
			<disponibilita>si</disponibilita>
			<collocazione>05.02.20.053.BIB</collocazione>
		</audiovisivo>
	</film>
	
	<film>
		<audiovisivo>
			<nome>Nome 2</nome>
			<cognome>Cognome 2</cognome>
			<titolo>Titolo 6</titolo>
			<nazione>Italia</nazione>
			<lingua>Italiano</lingua>
			<colore>BN</colore>
			<durata>1000</durata>
			<tipologia>Documentario</tipologia>
			<formato>Blu-ray</formato>
			<annoProduzione>2001</annoProduzione>
			<disponibilita>si</disponibilita>
			<collocazione>06.02.20.053.BIB</collocazione>
		</audiovisivo>
	</film>
	
	<film>
		<audiovisivo>
			<nome>Nome 1</nome>
			<cognome>Cognome 1</cognome>
			<titolo>Titolo 6</titolo>
			<nazione>Italia</nazione>
			<lingua>Italiano</lingua>
			<colore>BN</colore>
			<durata>1000</durata>
			<tipologia>Documentario</tipologia>
			<formato>Blu-ray</formato>
			<annoProduzione>2001</annoProduzione>
			<disponibilita>no</disponibilita>
			<collocazione>07.02.20.053.BIB</collocazione>
		</audiovisivo>
	</film>
</archivio>
